Help("""
Invocation:

    Make:
    $ python scons-local-2.1.0/scons.py

    Clean:
    $ python scons.py -c

    Quiet:
    $ scons -Q

""")

import os

link_libs = 'LabJackM'
ccflags = '-g -Wall'
env = Environment(CCFLAGS = ccflags)

examples_src = Split("""
    callback_stream.c
    o_stream_only.c
    o_stream_run.c
    o_stream_update.c
    stream_all_or_none.c
    stream_burst.c
    stream_example.c
    stream_triggered.c
""")

# Make
for example in examples_src:
    lib = env.Program(target = os.path.splitext(example)[0], source = example, LIBS = link_libs)


